version: 0.2

run-as: root

env:
  parameter-store:
            DB_HOST: "/rachit/DB_HOST"
            DB_NAME: "/rachit/DB_NAME"
            DB_USER: "/rachit/DB_USER"
            DB_PASSWORD: "/rachit/DB_PASSWORD"


phases:
   pre_build:
     commands:
       - apt update
       - apt upgrade -y
       - apt autoremove --purge
       - apt install nginx -y
       - apt install php php-fpm -y

   build:
     commands:
        - echo "build application"
       

artifacts:
  files:
    - echo "Upload artifact to bucket for deploy"
    - '**/*'


